### ISSUE TITLE
Prettify the URLs

### ISSUE THREAD

**Issue by doomspork** [beam-community/elixir-companies#449]
I think we should use `slugs` for industries than the raw `id` field.  For instance, I think `http://beta.elixir-companies.com/industries/156` should become something like :
- `http://beta.elixir-companies.com/customer-service`
- `http://beta.elixir-companies.com/industies/customer-service`

Or maybe we want to ditch the search-by-industry and build a more powerful search page. That could satisfy sorting by industry, #13, and potentially even #14.

- `http://beta.elixir-companies.com/companies?industry=customer-service`

Thoughts @gemantzu, @shawnonthenet, and others?

**Comment by gemantzu** [comment]
@doomspork maybe close this? we are not displaying information per industry (or maybe we can add that?)

**Comment by doomspork** [comment]
@gemantzu feel free to close issues you think we can do away with, just leave a comment 👌
