### ISSUE TITLE
Freelancer profiles

### ISSUE THREAD

**Issue by doomspork** [beam-community/elixir-companies#463]
We have companies, we have jobs, it makes sense that we also allow freelancers to list themselves and when they're available for hire.

Thoughts on what this should look like @tajchumber, @burden, and @gemantzu?

**Comment by tajchumber** [comment]
I don't see why not! I think it's a good idea!

**Comment by doomspork** [comment]
What kind of fields do we want to store for freelancers?

**Comment by gemantzu** [comment]
Let's see:
- Name (from github)
- Username (from github)
- email (from github)
- bio
- interested_in (a generic field to describe what jobs interests this person)
- (remote / on site / freelance)
- location (we can probably use this if we add functionality to search by location, when someone registers on the jobs board, we can show hiring companies near that person).
- (optional) maybe an amount field for a freelancer.
- (optional - may need permission) github account image (or generic one if not permitted)

**Comment by Nitrino** [comment]
In addition to @gemantzu fields described, you can add a link to CV, since I do not think that this section is aimed at providing complete information about the freelancer.

**Comment by sandeshsoni** [comment]
In addition to @gemantzu adding stackoverflow profile would also be helpful. My personal opinion

**Comment by gemantzu** [comment]
Check out #587 . Any additional fields are welcome for discussion.

**Comment by doomspork** [comment]
@sandeshsoni and @Nitrino would you mind taking a peek at @gemantzu's PR when you get a moment? He's implemented the version iteration of this.

**Comment by sandeshsoni** [comment]
perferct!

hey @doomspork , I see there is a CV_link, that really helpful.
Yes, on the external page that opens as CV, one can mention his stack-overflow link, hence my question is solved.

**Comment by doomspork** [comment]
Wonderful! We can get this launched and iterate on it as we come up with new ideas.

I would _love_ to revisit the entire sites UX and design, improving these profiles along the way. Any feedback you have is more than welcomed!

Thanks again for your involvement :tada:

**Comment by gemantzu** [comment]
#587 has been merged. Please let us know if you have any issues.
