### ISSUE TITLE
Add PostGIS to the project

### ISSUE THREAD

**Issue by doomspork** [beam-community/elixir-companies#494]
In order to provide the best support for location support and mapping companies/jobs/freelancers, we should encode locations into lat/lon. To properly store this we should look at using PostGIS in this project and adding a `point` to the company table to store the exact location of the company.

How do we handle companies would multiple locations? Do we even bother supporting that or require a single headquarters? Is a `point` of `nil` sufficient for us to determine the company as being truly "remote" and without any office?

Thoughts @tajchumber, @zacck, @gemantzu?

**Comment by Nitrino** [comment]
I think we can support multiple locations of companies and give the opportunity to indicate which of them is the main office.

Remote work should be a separate field, as there are companies with offices, but willing to hire remote workers. If remote work is indicated and there are no specified offices, then the company can be considered completely remote.

**Comment by doomspork** [comment]
The remote work should be reflected on the job listing. I'm referring to companies that have no office and thus, no locational to geo encode.

**Comment by Nitrino** [comment]
Yes, in this you are right, the ability to work remotely should be a field of an offer.
But I'm not sure that you can know whether the company is remote only by the presence of offices.
I known several companies that are remote but have offices for the convenience of some of their employees.

**Comment by doomspork** [comment]
> I known several companies that are remote but have offices for the convenience of some of their employees.

Me too. They'd list their locations 👍 

When I said this: 

> Is a point of nil sufficient for us to determine the company as being truly "remote" and without any office?

I'm only referring to companies that have no physical location: no office, no address, nothing to geo encode. They would be absent from this view and we need to decide if that's satisfactory or whether we want to display them in some other fashion.

This PR isn't concerned with displaying whether they allow remote workers.

**Comment by Nitrino** [comment]
@doomspork Oh, sorry. I'm lost in context.

**Comment by doomspork** [comment]
No worries @Nitrino! We _should_ open an issue about company enhancements. I think there's a number of things we can improve, an easy win would be supporting #443 (or any social network for the company).

I think collectively we can come up with a few more.
