### ISSUE TITLE
Showing less companies than intended

### ISSUE THREAD

**Issue by gemantzu** [beam-community/elixir-companies#516]
I have noticed this only on hiring for now, but it is an issue that keeps coming back.

![issue](https://user-images.githubusercontent.com/4966172/57072275-ce8a6e00-6ce5-11e9-8e71-10602fca03a7.png)

**Comment by doomspork** [comment]
@gemantzu please don’t auto assign all of your bug reports to me, no one else will do them if they think they’re being worked on.

Why don’t you open a PR instead? :grinning:

**Comment by lccezinha** [comment]
@gemantzu Have you been able to reproduce it locally, It will make easier to track the possible bug and fix it.

**Comment by gemantzu** [comment]
I think it has something to do with having more jobs on one company, but I will check it out this afternoon when I get back home. Thanks @lccezinha .

**Comment by doomspork** [comment]
@gemantzu anything I can do to help you reproduce this so folks can take a stab at fixing it?

**Comment by gemantzu** [comment]
I don't think you need to, I think I am like 99% right on this one. If you check our current hiring first page, there are three cards missing, and the companies listed are 13 and have actually 16 jobs (+1 one on one company and +2 one another). I am looking at it right now on how to fix.

**Comment by gemantzu** [comment]
Not an issue any more since we changed the mechanism of displaying companies / jobs.
