### ISSUE TITLE
machine-friendly data format?

### ISSUE THREAD

**Issue by RichMorin** [beam-community/elixir-companies#518]
I'd like to be able to download and/or upload company information in a machine-friendly data format (eg, JSON, TOML, YAML). If this is already possible, please document it. If not, please consider supporting this feature.

**Comment by doomspork** [comment]
@RichMorin that isn't currently possible but a PR to implement such a feature would be welcome 😁

**Comment by RichMorin** [comment]
> On May 28, 2019, at 14:58, Sean Callan <notifications@github.com> wrote:
> 
> @RichMorin that isn't currently possible but a PR to implement such a
> feature would be welcome 😁

https://github.com/beam-community/elixir-companies/blob/master/mix.exs
tells me that you're using Phoenix.  So, routing URLs should be trivial.  Also,
we're not trying to create an API for the site; we just want (at the moment :-)
to view and update the company table.

I have no doubt that I could create a reasonable first cut at a data structure
for a company table.  However, if you have a preference, I'd be happy to learn
about it.

Returning a single data structure in some arbitrary serialization format should
be trivial.  I'd probably start with JSON, for inter-language compatibility and
maximum reach, but I'd also want to support others such as TOML and/or YAML.

A basic API would just add `?fmt=<fmt`>` to each page's URL.  You're already
handling data subsets (eg, a-e), so we can leverage that.  However, in the longer
term I wonder if it might not be better to use GraphQL.  Thoughts?

I should warn you that I have some concerns about internal APIs, particularly
on the data storage side of things.  I only have incidental experience and some
theory about relational databases, and I've never used Ecto or PostgreSQL as a
developer.  So, some hand-holding will probably be needed and advisable.  Here
are some basic questions, to get us started:

Q: Do you have a preferred external API, naming conventions, etc?  Is there a
convention, such as CRUD, that you'd like to follow?

Q: What internal API would you suggest for the controllers?  I need to know
how to hand requests and submissions on to Ecto the rest of the system.

Q: Where should I look for documentation or other information on the data
structure(s) used to store information about listed companies?

-r

**Comment by doomspork** [comment]
Howdy @RichMorin, I can certainly do the development work. Could you explain your needs a little better? I'm not entirely sure what you mean by: 

> Also, we're not trying to create an API for the site; we just want (at the moment :-)
to view and update the company table.

**Comment by RichMorin** [comment]
> On May 28, 2019, at 18:44, Sean Callan <notifications@github.com> wrote:
> 
> Howdy @RichMorin, I can certainly do the development work.

If it isn't too much trouble for you, I won't complain about missing out
on the development work.  However, if there are parts you'd like me to
take on, just say so.

> Could you explain your needs a little better? I'm not entirely sure what you mean by:
> 
> Also, we're not trying to create an API for the site; we just want (at the moment :-)
> to view and update the company table.

OK, let's start by tackling the downloading half of the issue.  If we can get that
working, we can worry about uploading new or modified entries.

Looking at the site, I see a number of URLs for accessing information, eg:

  https://elixir-companies.com/en/                       # Recent Additions
  https://elixir-companies.com/en/browse/                # Newest
  https://elixir-companies.com/en/browse/?type=ae        # A-E
  https://elixir-companies.com/en/browse/?type=hiring    # Hiring

Based on the pattern given in https://hexdocs.pm/phoenix/routing.html,
the JSON version of the last URL could be one of the following:

  https://elixir-companies.com/api/en/browse/?type=ae
  https://elixir-companies.com/en/api/browse/?type=ae
  https://elixir-companies.com/api/browse/?type=ae

However, I'd prefer a URL format that can support a variety of data formats
and doesn't get in the way of language or other preferences.  For example:

  https://elixir-companies.com/en/browse/?type=ae&fmt=json

Unfortunately, this still doesn't handle the question of pagination.  So, maybe
we could have parameters that control the page number and size.  If I wanted to
get all of the hiring companies, for example, I could make this request:

  https://elixir-companies.com/en/browse/?type=hiring&fmt=json&page=1&size=9999

Is any of this starting to make sense?

-r

**Comment by RichMorin** [comment]
FYI, I'm currently engaged in a discussion of some of these issues on

https://elixirforum.com/t/is-there-a-best-practice-for-forming-json-etc-urls/22747

-r

**Comment by doomspork** [comment]
@RichMorin apologizes for any confusion. I'm clear on _how_ to implement support for different formats in an API. I'm unclear on _why_ we want to do that here 😁 

Could you help me understand _why_ you're asking for machine-friendly access to the list of companies with the ability to both download and later upload them? 

What is the business need we're trying to fulfill with this feature? I want to understand that before we build anything, so we can consider both your use-case and others that may arise.

**Comment by RichMorin** [comment]
> On May 29, 2019, at 11:13, Sean Callan <notifications@github.com> wrote:
> 
> @RichMorin apologizes for any confusion. I'm clear on how to implement support for different formats in an API. I'm unclear on why we want to do that here 😁

Although JSON is the most popular (and thus best supported) format for serialization of web-based data, it isn't all that pleasant for humans to read. So, for convenience, I generally use YAML or TOML instead.

I realize that I could download the JSON and then transform the data into my preferred format, but this involves an extra step.  A site's TOML or YAML emitter can also be optimized to generate clean and readable files, based on the structure of the data involved.  

> Could you help me understand why you're asking for machine-friendly access to the list of companies with the ability to both download and later upload them?

My reason for wanting the ability to download company information is simply that I like to be able to process and store information in arbitrary ways.  For example, I might want to search for a particular keyword, add my own annotations or keywords, etc.  If I have the data, I can do this; otherwise, I can only access the data in ways that its developers supported.

My reason for wanting the ability to upload information is more speculative.  Mostly, it strikes me that there are some other sources of company information (eg, Elixir Forum job postings).  I could imagine cleaning up some of this data and wanting to upload it.  By providing an API for uploading, the site could support that.

I also imagine that downloading and uploading APIs could enable the use of an SPA with more capabilities and convenience than the current site offers.

-r
