### ISSUE TITLE
icon-purle ?

### ISSUE THREAD

**Issue by RichMorin** [beam-community/elixir-companies#519]
Looking at the HTML for https://elixir-companies.com/en/browse, I noticed a possible typo:

  <span class="icon icon-purle" >

Should this be icon-purple?

**Comment by gemantzu** [comment]
Hi @RichMorin . Can you be more specific? Where exactly is the typo? What does it say?

**Comment by Nitrino** [comment]
Sori guys, I saw your conversation and it seemed to be more quickly fixed than discussed.

**Comment by tajchumber** [comment]
thanks @RichMorin for bringin this issue up :)
