### ISSUE TITLE
completeness, order, and searching

### ISSUE THREAD

**Issue by RichMorin** [beam-community/elixir-companies#523]
The site allows the user to select ranges of starting letters (eg, A-E) for company names. However, it does not have any way to display sorted lists of companies whose names do not start with a letter (eg, "2U", "500 Companies", "{sauce}"). There aren't too many of these, so they should probably be displayed before A or after Z.

I'd also like the main browsing page (https://elixir-companies.com/en/browse) and the hiring page (https://elixir-companies.com/en/browse?type=hiring) to list companies in alphabetical order.

Finally, I'd like to have ways of searching for companies by keyword, name, etc. Clicking through a series of "next" links is quite tedious.

**Comment by gemantzu** [comment]
I have been working on a live view version of the website, where we can have multiple filters, but i haven't had the time to finish unfortunately. Hopefully, i will pick it up again next week. This should solve most of the issues you have, but i can't predict when i will be done, since my free time is very limited these days.

**Comment by eaverdeja** [comment]
@gemantzu would you like some help?

I am by no means an expert Elixir developer, but I'm studying and have been tinkering with LiveView (I'm creating a LiveView interface for the Islands game built in the [Functional Web Development with Elixir, OTP, and Phoenix](https://pragprog.com/book/lhelph/functional-web-development-with-elixir-otp-and-phoenix) book)

**Comment by gemantzu** [comment]
@eaverdeja my free time has been limited to almost zero, that's how this has stagnated. I will have some free time at the end of the week, I will try to revise what I have, upload it here as a wip and we can discuss about any improvements you might have to suggest. Thanks.

**Comment by eaverdeja** [comment]
@gemantzu Sure, that works for me!

**Comment by gemantzu** [comment]
@eaverdeja as promised, here is where I have landed so far. Feel free to contribute. #526

**Comment by gemantzu** [comment]
Closing this since the site now uses a different approach of searching (which solves most of @RichMorin 's suggestions). Thank you all for the discussion.
