### ISSUE TITLE
Have "remote" option in UI and accessible via a url, perhaps "/browse?type=hiring&remote=true"

### ISSUE THREAD

**Issue by AdamT** [beam-community/elixir-companies#532]
Are there any plans to allow filtering companies that are hiring remote? Right now that option isn't available in the UI and as far as I can tell, is not available via a URL.

I think it would be useful to:
1. Add filtering by remote in the UI
2. Add filtering remote via a URL `browse?type=hiring&remote=true`

In the UI this could be a checkbox/link that once clicked reloads the results that have a remote job and updates the URL.

**Comment by gemantzu** [comment]
@AdamT yes this is under construction. I had the initial idea to make it a LiveView thing with infinitescroll and text search but it is not working properly. We will see how we will implement it, but jobs will be searchable / filterable.

**Comment by AdamT** [comment]
@gemantzu That's great. Really looking forward to it.

Perhaps before going all LiveView on a filtering feature, maybe a good V1 version would to render a page based on query parameters. This may work well as a quick implementation since ya'll have pagination already implemented. Anyhoo, just a thought. Thank you so much for all the great work! 👏 🙇

**Comment by gemantzu** [comment]
That's why I said I had the initial idea, it probably can't work with LiveView the way I intended it. We are working on it with alternatives, but thank you for the insight anyway!
