### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by gemantzu** [beam-community/elixir-companies#533]
@doomspork / @tajchumber / @burden I am creating this post so we can have a clear roadmap of the things we want to change in this repository / app.

Please state your thoughts on the list below:
- ~Remove hiring filter and create a new route for jobs~
- ~Filter / Search / Sort companies and jobs~
- Restructure Company ~/ Job List page~
- Company Details page (Logo?)
- Move delete buttons to edit pages
- Twitter Feed
- Job locations (we add an address, so we can have a per area filter later on - clicking remote on the form should disable and empty the location)
- ~Freelancer Profiles (we have an open issue about that, good as food for thought, we can also make the user add an address so he can filter jobs per their location)~
- ~(backend) Improve comparison of edits~
- (backend) block multiple entries / editions per company
- (backend) Clear / merge industries
- ~(backend) Finish Email Notifications~
- Theme additions (any thoughts @burden / @tajchumber ?)
- Admin auto accept (if the user submitting a company / job is on the maintainer list, auto accept the change)
- Code Coverage (now @ 47.5%)

**Comment by doomspork** [comment]
#### Remove hiring filter and create a new route for jobs

I think that's a great idea and an easy win for Hacktoberfest

#### Filter / Search / Sort companies and jobs

We could absolutely improve the filter / search / sort of companies. We could also expand on the company profiles and provide a dedicated company page which could include a summary of how Elixir is used, company employee count, etc.

#### Job locations 

We need to do this. Absolutely.

#### Freelancer Profiles

I'm kind of torn on this. How are we going to make these at all sortable / filterable in a meaningful way? The best kind of advertisement for a freelancer would be getting involved in the project and demonstrating those skills.

I would put this further down the list of things to accomplish. It _could_ be an opportunity to ask for a donation or charge a small listing fee. Those funds could be used by Elixir School or BEAM Community for community efforts. Even then I still see this being of lower priority.

#### (backend) Improve comparison of edits

I'm open to suggestions. We've got is a very simple solution I whipped together. Maybe we could explore more of a wiki-style? Thoughts @burden?

#### (backend) block multiple entries / editions per company

This would be smart. We should also update the verbiage so when people submit a new company / job they understand it will be reviewed before appearing on the site.

#### (backend) Clear / merge industries

Definitely. Someone just open a PR and let's go from there.

#### (backend) Finish Email Notifications

I will do that this weekend with #513

**Comment by gemantzu** [comment]
#534 Solves first two (although it needs improvement on the looks).
What kind of PR can we do for industries? They are on database entries.

**Comment by doomspork** [comment]
I think we have some options maybe?

1. We could write a migration, run it, and delete it.
2. We could write a Mix Task and delete it as well
3. We could run a one-off script without checking it into source control but this would impact the ability to review it.

**Comment by tajchumber** [comment]
looks good to me @doomspork @gemantzu

**Comment by maartenvanvliet** [comment]
I have couple of ideas:

* Add company logo 
Either direct image url or upload to s3
* Twitter feed of companies
Much like https://elixirstatus.com/ does, when companies are created they are also posted to a twitter feed

**Comment by gemantzu** [comment]
@maartenvanvliet thank you for your contributions! Company logo is under discussion already, but twitter feed is a really nice idea imo. Thank you!

**Comment by doomspork** [comment]
Great ideas @maartenvanvliet! I’ve got the elixir-companies twitter handle, we just need to build the notifications 🎉

**Comment by doomspork** [comment]
I am going to investigate the LOE for the twitter integration over the next few days. 

We could see if a service like Cloudinary offers a free tier for open source projects, that would tackle the company logo uploads. That said, using S3 would present a neat opportunity to move the entire application to AWS and possible use Terraform to provide an example to the community. It would also be a wonderful blog post for Elixir School.
