### ISSUE TITLE
Support markdown in company description

### ISSUE THREAD

**Issue by maartenvanvliet** [beam-community/elixir-companies#536]
The description for  https://elixir-companies.com/en/companies/4/edit has some markdown to link to github repositories. See below for the markdown. 

Right now this is not supported. This would not be hard to implement imo but should it be supported?

```
Mobile and web app design and development services, using Elixir / Phoenix, React, and React Native. Based in Portland, San Francisco, and remote across the USA, with clients in eight countries. We build and maintain dozens of popular open source libraries, including [Thesis](github.com/infinitered/thesis-phoenix) and [Torch](github.com/infinitered/torch).
```

**Comment by doomspork** [comment]
@maartenvanvliet we've been talking about some site improvements lately and this should definitely be one of them! Would you be open to submitting a PR? If not I think I can tackle this for us.

In addition to this enhancement some of the other things I'm thinking are a dedicated page for each company with a larger section for text, links to project repos, and all current job listings. I'm all ears when it comes to feedback 😁

**Comment by maartenvanvliet** [comment]
Great! Will do :)
