### ISSUE TITLE
Pending Changes ... changes not showing properly

### ISSUE THREAD

**Issue by gemantzu** [beam-community/elixir-companies#571]
![Screenshot from 2019-12-15 10-44-23](https://user-images.githubusercontent.com/4966172/70860232-ed154080-1f27-11ea-85e1-70974331044a.png)

We have a bunch of changes from this user, but it is not visible what they do change (I can't find a change inside them to be honest, text seems the same for all cases).

**Comment by doomspork** [comment]
The other oddity is that these are labelled updates when there is no `id` in the change :thinking:

**Comment by gemantzu** [comment]
Eh? meaning? The companies exist though, they are not new.

**Comment by doomspork** [comment]
If you look in the admin panel you will notice these all say "update" but if you look at the JSON in the changes there is no `id`. That itself is a bug. If no `id` is present then it should be a new record and thus a "create" action

**Comment by gemantzu** [comment]
Ah, ok. Didn't know about this detail.

**Comment by gemantzu** [comment]
This was probably fixed by #582 right?
