### ISSUE TITLE
Pending Change CRUD for admins

### ISSUE THREAD

**Issue by gemantzu** [beam-community/elixir-companies#589]
Right now we have some PendingChanges that cannot be touched due to a bug we used to have. Most of them PendingChanges can be safely deleted (Idk how they came to be in the first place, one user put them all in with no apparent change in them). Should we have a delete button in the table in those situations?

**Comment by doomspork** [comment]
@gemantzu is this still a bug?

**Comment by gemantzu** [comment]
Yes! If you see the pending changes on the production system, they can't be handled and they produce an error.

**Comment by tajchumber** [comment]
it doesn't seem to be a problem for me anymore?
Can you still replicate this? @gemantzu @doomspork

**Comment by gemantzu** [comment]
hey @tajchumber ! I was now able to reject the changes with not a company id on them (wasn't able to before), but the last one cannot be handled (the delete one). Checking on the actual issue now.

**Comment by tajchumber** [comment]
@gemantzu i was able to reproduce this bug locally
I will open a PR to fix this!

**Comment by doomspork** [comment]
Hooray! Thanks for helping get this resolved @tajchumber.

@gemantzu / @tajchumber I'm happy to re-think the way we do these pending changes if think there may be a better way?

**Comment by tajchumber** [comment]
I think the way this works is fine! :)

The issue is caused by an edge case that no one thought of or tested. I don't think I would have caught it if it didn't cause the site to crash at all!

I have opened a [PR](https://github.com/beam-community/elixir-companies/pull/600) for it, please review :)
