### ISSUE TITLE
Profile page button placement (only in production for some reason)

### ISSUE THREAD

**Issue by gemantzu** [beam-community/elixir-companies#592]
![Screenshot from 2020-02-22 19-25-27](https://user-images.githubusercontent.com/4966172/75096667-77be8f80-55aa-11ea-8d74-36db20fa845f.png)
This is only showing up like that in production. In my development environment you can see it below:

![Screenshot from 2020-02-22 19-36-51](https://user-images.githubusercontent.com/4966172/75096692-b9e7d100-55aa-11ea-98a0-9b2e7fe9e868.png)

**Comment by doomspork** [comment]
@burden any idea? You're the UX pro in this neck of the woods.

**Comment by gemantzu** [comment]
solved by #593
