### ISSUE TITLE
job showing in recent while it is deleted.

### ISSUE THREAD

**Issue by gemantzu** [beam-community/elixir-companies#604]

**Comment by doomspork** [comment]
@gemantzu we need to provide some details or context on these reports so people other than yourself can look into them.

**Comment by doomspork** [comment]
I don't see a job listed there. Are you referring to the "Hiring" flag?

**Comment by gemantzu** [comment]
The problem is in the companies query (recent, all), we are returning all jobs, even if they are "deleted".

**Comment by doomspork** [comment]
I understand @gemantzu. I'm asking for clarification because you didn't add any context to this bug report.  As I've asked before: Please do not just open empty issues. The goal is to provide something others can contribute to and help fix. Issues like this are left to you and you alone to fix.
