### ISSUE TITLE
:single_one_for_one deprecation

### ISSUE THREAD

**Issue by gemantzu** [beam-community/elixir-companies#606]
Here is the message:

```elixir
warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.2) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.2) lib/supervisor.ex:556: Supervisor.start_link/2
  (kernel 6.4.1) application_master.erl:277: :application_master.start_it_old/4
```

Erlang / Elixir versions:

```elixir
Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]

IEx 1.10.2 (compiled with Erlang/OTP 22)
```

**Comment by doomspork** [comment]
This is the most frustrating error. It's happening all over the place but there isn't a set solution AFAIK. I've seen many questions about this online

**Comment by pau-riosa** [comment]
hi guys I think this one might help regarding the warning https://hexdocs.pm/elixir/DynamicSupervisor.html

**Comment by gemantzu** [comment]
Thanks @pau-riosa ! You are welcome to push a PR if you want :)

**Comment by pau-riosa** [comment]
wow really thanks! I'll try!

**Comment by tajchumber** [comment]
I think this is not an issue anymore. can we close it @gemantzu ?

**Comment by gemantzu** [comment]
@tajchumber really? Did something change on erlang / elixir which fixed it or what? I am sorry, I was away for a few days.

**Comment by tajchumber** [comment]
I think it might be after updating to elixir 1.10? I actually didn't notice when it stopped happening haah
