### ISSUE TITLE
Switch from Heroku to Gigalixir

### ISSUE THREAD

**Issue by bglusman** [beam-community/elixir-companies#620]
@doomspork and I discussed this a month or so ago but I don’t believe we documented anywhere and I just thought of it again.

Also came across this while looking at Github actions to enforce mix formatting which reminded me so may as well include the link here as may be helpful:
https://github.com/mhanberg/gigalixir-action

**Comment by doomspork** [comment]
@bglusman I signed up today and I tried to invite you. Let me know if you got anything, it gives me no indication it sent.

**Comment by bglusman** [comment]
I don’t appear to have any new email from them... I may have made an account a few years ago but not sure/may have been old work address if I did... We’ll figure it out soon though

**Comment by doomspork** [comment]
Thanks for looking into this again @bglusman! For those not in Slack, at this time Gigalixir requires a paid account to have multiple users :-1:
