### ISSUE TITLE
search or filter by location

### ISSUE THREAD

**Issue by bradyfontenot** [beam-community/elixir-companies#624]
Really appreciate you guys aggregating all these companies.  It would be great if it was possible to search companies by country either through the current text search or via filter options.  Currently the text search doesn't return results based on company.

**Comment by tajchumber** [comment]
This has been implemented in https://github.com/beam-community/elixir-companies/pull/627 so I'm closing this issue

Thanks for the request @bradyfontenot :)

**Comment by bradyfontenot** [comment]
nice! I really appreciate it. Thanks.
