### ISSUE TITLE
Edit function does not appear to work

### ISSUE THREAD

**Issue by GregLMcDonald** [beam-community/elixir-companies#629]
There is a small grammar error in our company entry (http://elixir-companies.com/en/companies/634) that I am trying to fix (change "client's" to "clients'") using the Edit action which is available when I am logged in with the GitHub account.  However, when I hit save, the entry remains unchanged.  Maybe you need admin permissions to edit?

If the Edit action is available, I would expect to see the changes in my listing when I click Save.

**Comment by doomspork** [comment]
![image](https://user-images.githubusercontent.com/73386/96480988-28dbff00-11f8-11eb-8b9c-88007caf3da3.png)

Howdy @GregLMcDonald! All changes require admin approval (we've had abuse). It can take a bit for one of us get online and get to the queue. Sorry for the delay. We're always looking for ways to improve the site :+1:

**Comment by rathorevaibhav** [comment]
hey @doomspork 
I'm also facing a similar situation and wanted to update my company description. I went to edit page but clicking on save yields no success.

Is the edit feature currently working or should I wait for the new description approval from someone? Please guide. TIA!

**Comment by rathorevaibhav** [comment]
hey any update on this? I was trying to update the description for our company:
http://elixir-companies.com/en/companies/654

**Comment by doomspork** [comment]
Hi @rathorevaibhav as I mentioned in the original reply, this is not a bug. This is the human admins being busy with personal lives and not having a chance to review things.  Someone will get to it shortly.

Unfortunately admin approval is required as a result of some bad actors.

**Comment by rathorevaibhav** [comment]
@doomspork thanks for your update. I understand the bad actors and it gets difficult with them.

**Comment by doomspork** [comment]
You should have gotten some emails from the site. I went through your submissions :+1:

**Comment by rathorevaibhav** [comment]
Thank you very much for that! Yes, my submission has been approved. Much appreciated! 👏

**Comment by doomspork** [comment]
You're very welcome. Thanks for the contribution @rathorevaibhav :grin: 

Once I finish the major overhaul of Elixir School I'm going to revisit Elixir Companies in the hopes of improving the UX for both viewers and submitters.
