### ISSUE TITLE
Adding company process not explained on website itself

### ISSUE THREAD

**Issue by raymondboswel** [beam-community/elixir-companies#635]
HI there! 

I tried adding my employer to the list, and didn't see it appear, which caused me to try again a few more times. The readme in this repo explains the process perfectly well, but there is no explanation on the site itself. I'm happy to make a PR if no one else wants to. Let me know :+1:

**Comment by doomspork** [comment]
Howdy @raymondboswel! That would be really helpful!

Truth be told I've really been wanting to revisit this site and overhaul it. The admin approval process worked for awhile but now it's proving to be a bottle neck. Perhaps we could figure out a better solution relying on Elixir configuration files or yml.

**Comment by raymondboswel** [comment]
I see the site is internationalized, I can do the English version, but will need help with the rest.
