### ISSUE TITLE
New Elixir companies website

### ISSUE THREAD

**Issue by szsoppa** [beam-community/elixir-companies#661]
Hey guys!

I really liked the old elixir-companies site, and I think it's what the community needs to popularize this language. CTOs and lead devs often make the tech decision based on its adoption in big brands, and this type of listing helps them (and us too) orientate what's the current state of adoption.

Long story short, I decided to create a new website, as I think, after reading this thread: https://github.com/beam-community/elixir-companies/issues/649, the old site may not come back at all.

Check it out here: https://elixir-hub.com. While creating an MVP, I realized there is much more we can do here than just list companies. Elixir lacks a hub, where devs could easily filter through various parameters, and various resources, such as:
- jobs,
- books,
- podcasts,
- blogs
- many more

I encourage you to help me build this listing by adding new resources, and for now - companies :)

**Comment by doomspork** [comment]
Howdy @szsoppa! I've been out of pocket due some deaths in the family, but we're actively working on bringing the site back online with some changes to make managing it easier: https://github.com/beam-community/elixir-companies/pull/660

**Comment by szsoppa** [comment]
Hey, @doomspork, it seems like I should have dug a bit more into open branches. Clearly, I made some wrong conclusions (sorry for that), but... I still think a hub can be an interesting space. Different resources are spread across different places, so I think it's worth exploring how it would work to have it all on one site.

All in all, great to hear that the site is up and running :)

**Comment by doomspork** [comment]
https://elixir-companies.com/en We're live 🎉 I'm working through adding companies as I review each on the previous site (There's more than a few on there I know have moved away from Elixir).

Feel free to add more yourself 🎉 https://github.com/beam-community/elixir-companies/tree/main/priv/companies
