### ISSUE TITLE
Search by company name or industry is not working

### ISSUE THREAD

**Issue by samuelpordeus** [beam-community/elixir-companies#669]
After the overhaul, when trying to search by both company name or industry we don't get any results as a response.

![search attempt](https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExNWEwMDQ0NDQ0NWE2ODUzMjE2NDQ2NmU2N2Y0NGNiMjM2MjA2MWUxOCZjdD1n/Ax1KtjLkOEgzpphQ10/giphy.gif)

We are planning to work on that as soon as we can but help is more than welcome ❤️

**Comment by vvuunnqq** [comment]
I think it's not a bug.
I see that `searched_list` func in `lib/companies/helper.ex` does nothing :D

**Comment by imahmedismail** [comment]
How can I contribute to this issue? I've the fix ready for it but can't push the branch and create a PR for it. 
cc: @samuelpordeus

**Comment by imahmedismail** [comment]
<img width="1137" alt="image" src="https://github.com/beam-community/elixir-companies/assets/84928463/67628e4f-21c7-40cd-a62d-ab8d9f413446">

<img width="1013" alt="image" src="https://github.com/beam-community/elixir-companies/assets/84928463/0c997670-e2fb-4f12-b234-669028aff2da">

**Comment by imahmedismail** [comment]
Found a way, this is the PR: https://github.com/beam-community/elixir-companies/pull/693
cc: @samuelpordeus
