### ISSUE TITLE
Update `get_company!` to work without Ecto

### ISSUE THREAD

**Issue by doomspork** [beam-community/elixir-companies#672]
https://github.com/beam-community/elixir-companies/blob/main/lib/companies/companies.ex#L55-L71

**Comment by vvuunnqq** [comment]
Hi, is this func is used for query+update company profile?
If yes, I think the id should be related to company files name in `priv/companies`.

**Comment by doomspork** [comment]
Howdy @vvuunnqq! We don't allow updating companies via the site at this point so that usage is no longer necessary. I believe this is only used when we use the show route for a company.

> If yes, I think the id should be related to company files name in priv/companies.

Agreed! Happy to yield to you here. We did discuss slugs before: https://github.com/beam-community/elixir-companies/issues/588

**Comment by vvuunnqq** [comment]
hmmm, I'm not sure at all, just create a PR #679 to support url slug 😁
