### ISSUE TITLE
Obsolete companies

### ISSUE THREAD

**Issue by tsubery** [beam-community/elixir-companies#737]
Looks like the companies in the following files are not in business anymore. How do you handle such cases? 
They can be removed or be linked to an archive pages using something like [Wayback Machine](https://web.archive.org/) to keep the historical record. Maybe there should be a separate section for companies that used to use Elixir and stopped.

> priv/companies/beamjobs.exs
priv/companies/briisk.exs
priv/companies/formulae.exs
priv/companies/grasp.exs
priv/companies/imby_bio.exs
priv/companies/mydreams.exs
priv/companies/seekpanda.exs
priv/companies/shopybot.exs
priv/companies/woumedia.exs

**Comment by doomspork** [comment]
Howdy @tsubery! Historically we've just removed the companies but I'm open to ideas about an archive. Thoughts @beam-community/team?

**Comment by davydog187** [comment]
What would be the purpose of keeping around a graveyard of Elixir companies? I personally think deleting them is better to show the active members of the community
